version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
